<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FileNamingManager.Application\FileNamingManager.Application.csproj" />
    <ProjectReference Include="..\FileNamingManager.Core\FileNamingManager.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="..\..\assets\file-naming-32.png" Link="Assets\file-naming-32.png" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FileNamingManager.UnitTests" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
